### ISSUE TITLE
Admin create topic promise handler not always updated after topic creation

### ISSUE THREAD

**Issue by mensfeld** [karafka/rdkafka-ruby#266]
Not sure why but I've seen this happen once in a while.

I bypassed this in Karafka but a proper fix would be expected.

Under heavy load, Kafka does create those topics and it does that in a timely fashion but for any reason promise ain't updated.

**Comment by patelvp** [comment]
It might be related or a completely new issue. I have a simple script that lists all the topics that are already there on our Kafka server and tries to create only new topics.
I have two Kafka servers running locally on ports `9092` and `29092`.
Noticed with the admin client the `.metadata.topics` method call returns topics from the right server from the `Rdkafka` config (`29092` in this case). But when creating the topic using `.create_topic`, it tries to create the topic on the server on the port `9092`. When killing the server on `9092`, I ran into the same issue of a timeout, which is probably obvious since the server is not present on 9092 port anymore. 
After writing this, it feels like it's its own issue. LMK if you want me to create a new issue.
Thanks for your active contribution to this project.

**Comment by mensfeld** [comment]
@patelvp sounds like a separate issue if that is true. Please make sure to create a repro.

**Comment by mensfeld** [comment]
Closing. I was not able to reproduce it after we switched to using mutex lock instead of polling. I'm not saying it is fully fixed but I can't repro anymore.
