### ISSUE TITLE
SSL handshake failed: error:1416F086:SSL

### ISSUE THREAD

**Issue by edenisn** [karafka/rdkafka-ruby#522]
This is copy for an issue https://github.com/karafka/karafka-rdkafka/issues/128

I have two files: truststore.jks and another keystore.pfx

With command
`keytool -export -alias caroot -keystore truststore.jks -rfc -file ca-cert.pem`
I extract caroot cert for key - ssl.ca.location

Then, with command
```
export KEYSTORE_PASSWORD=password \
KEY_PASSWORD=password \
KEYSTORE=keystore.pfx \
CERTIFICATE=client.certificate.pem \
KEY=client.key && \
openssl pkcs12 -in "$KEYSTORE" -out "$CERTIFICATE" -nodes -passin "pass:$KEYSTORE_PASSWORD" && \
openssl pkcs12 -in "$KEYSTORE" -out "$KEY" -nocerts -passin "pass:$KEYSTORE_PASSWORD" -passout "pass:$KEY_PASSWORD"
```
I extract client public key for librdkafka key - ssl.certificate.location and private client key for librdkafka key - ssl.key.location

It seems to me that test connection with kafkacat working correctly:
`kafkacat -C -b broker:9095 -X security.protocol=SSL -X ssl.ca.location=ca-cert.pem -X ssl.certificate.location=client.certificate.pem -X ssl.key.location=client.key -X ssl.key.password=password -t topic_name `
got answer:
`% Reached end of topic topic_name [0] at offset 863365`

but, with karafka config in Rails:

```
config: {
  'bootstrap.servers': 'broker:9095',
  'security.protocol': 'ssl',
  'ssl.ca.location': 'ca-cert.pem',
  'ssl.certificate.location': 'client.certificate.pem',
  'ssl.key.location': 'client.key',
  'ssl.key.password': 'password'
}
```
then run code in rails console:
```
consumer = Rdkafka::Config.new(config).consumer
consumer.subscribe("topic_name")
consumer.each do |message|
  puts "Message received: #{message}"
end
```

got this error:
`[20124:21140 config.rb:45] Rails -- rdkafka: [thrd:ssl://broker:9095/bootstrap]: ssl://broker:9095/bootstrap: SSL handshake failed: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed: broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed (install ca-certificates package) (after 30ms in state SSL_HANDSHAKE, 1 identical error(s) suppressed)`

What is the problem may be?

```
Karafka version: 2.4.13
Ruby version: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
Rdkafka version: 0.17.6
Consumer groups count: 1
Subscription groups count: 1
Workers count: 5
Boot file: /karafka.rb
Environment: testing
License: LGPL-3.0
```

**Comment by mensfeld** [comment]
Hey, this is beyond my support because it would require me to understand your setup and examine your certificates and infrastructure in depth.

If you can create a reproduction docker setup, I will give it a look.

Aside from that, the error indicates that you are either missing a CA cert or the way you generate / export is not correct. I am not an expert in each cert configuration, so it's hard for me to give advice without getting my hands dirty with your setup. I know there can be few 

You can try setting `enable.ssl.certificate.verification` to verify if that's going to help (temporarily).

Aside from that, can you provide the extensive logs? The docs on how to enable them are here: https://karafka.io/docs/Problems%2C-Troubleshooting-and-Debugging/#enabling-extensive-logging
